In [124]:
import pandas as pd

## Оставьте в выборках только строки с классами positive и negative.

In [ ]:
df_test = pd.read_csv('rusentitweet_test.csv', index_col=0)
df_train = pd.read_csv('rusentitweet_train.csv', index_col=0)

In [125]:
df = pd.read_csv('rusentitweet_full.csv', index_col=0)
df

text     label  \
0                                   @varlamov @McFaul На      skip   
1      велл они  всё равно что мусор так что ничего с...  negative   
2      "трезвая жизнь какая-то такая стрёмная"\r\n(с)...  negative   
3      Ой какие неожиданные результаты 🤭 https://t.co...   neutral   
4      @Shvonder_chief @dimsmirnov175 На заборе тоже ...   neutral   
...                                                  ...       ...   
13387                 все пора спать пиздец словила шизу  negative   
13388  такими темпами я создам новую секту или органи...   neutral   
13389  Ты смотрела аниме, завернувшись в одеяло ,пока...   neutral   
13390                         @AlyonaPikachu Пиздануться  negative   
13391  Акция «Библионочь — 2020». Лисюткина А. читает...      skip   

                        id  
0      1327934765807308801  
1      1252943181387350017  
2      1323610669061677056  
3      1336231661160247297  
4      1292421736454127617  
...                    ...  
13387  1310349554911457286  
13388  1326638109317066752  
13389  1333159916505362433  
13390  1308341976455053312  
13391  1255780330260365317  

[13392 rows x 3 columns]

In [126]:
df = df[df['label'].isin(['positive', 'negative'])]
df

text     label  \
1      велл они  всё равно что мусор так что ничего с...  negative   
2      "трезвая жизнь какая-то такая стрёмная"\r\n(с)...  negative   
8                       @BTS_twt ты такой красивый 😭😭😭🥺💓  positive   
9                          @Ladyzchensk Цыган , хуле ...  negative   
11     @okdaa @wifeyoonminn @Y_Yoon_ Но ты очень крас...  positive   
...                                                  ...       ...   
13382  @_sasukedaisuki_ я не знаю что сказать просто\...  positive   
13384                 ладно всё делаю это ваше сраное дз  negative   
13385  66-летняя женщина пострадала на пожаре на улиц...  negative   
13387                 все пора спать пиздец словила шизу  negative   
13390                         @AlyonaPikachu Пиздануться  negative   

                        id  
1      1252943181387350017  
2      1323610669061677056  
8      1281551551706865665  
9      1257761690122358784  
11     1236273859671834624  
...                    ...  
13382  1284435123144994816  
13384  1249422155487629313  
13385  1237630704449736705  
13387  1310349554911457286  
13390  1308341976455053312  

[5712 rows x 3 columns]

## Определите и реализуйте креативные методы очистки набора данных.

re.sub(pattern, repl, string, count=0, flags=0)

pattern: Регулярное выражение, которое нужно найти в строке.

repl: Строка, на которую нужно заменить найденный фрагмент.

string: Исходная строка, в которой будет происходить поиск и замена.

count (необязательный): Количество замен (по умолчанию заменяет все вхождения).

flags (необязательный): Флаги для изменения поведения регулярного выражения (например, re.IGNORECASE для игнорирования регистра).

In [127]:
import re
from nltk.corpus import stopwords

stop_words = set(stopwords.words('russian'))
words_to_remove = {'не', 'всегда', 'лучше', 'никогда', 'хорошо', 'нет', 'нельзя', 'можно'}
for word in words_to_remove:
    stop_words.discard(word)

def clean_text(text):
    text = text.lower()
    
    text = re.sub(r'@[\w-]+', '', text) # убираем ссылки на людей. считаем что ники состоят из букв, цифр, нижних подчеркиваний и дефисов
    
    text = re.sub(r'[^\w\s]', '', text) # убираем все что не буквы. ^ = не

    text = re.sub(r'\s+', ' ', text).strip() # убираем лишние пробелы

    tokens = [word for word in text.split() if word not in stop_words] # stopwords
    
    return tokens

In [128]:
df.loc[:, 'clean_text'] = df['text'].apply(clean_text)
df

C:\Users\an23m\AppData\Local\Temp\ipykernel_12896\1428303760.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'clean_text'] = df['text'].apply(clean_text)


text     label  \
1      велл они  всё равно что мусор так что ничего с...  negative   
2      "трезвая жизнь какая-то такая стрёмная"\r\n(с)...  negative   
8                       @BTS_twt ты такой красивый 😭😭😭🥺💓  positive   
9                          @Ladyzchensk Цыган , хуле ...  negative   
11     @okdaa @wifeyoonminn @Y_Yoon_ Но ты очень крас...  positive   
...                                                  ...       ...   
13382  @_sasukedaisuki_ я не знаю что сказать просто\...  positive   
13384                 ладно всё делаю это ваше сраное дз  negative   
13385  66-летняя женщина пострадала на пожаре на улиц...  negative   
13387                 все пора спать пиздец словила шизу  negative   
13390                         @AlyonaPikachu Пиздануться  negative   

                        id                                         clean_text  
1      1252943181387350017               [велл, всё, равно, мусор, страшного]  
2      1323610669061677056  [трезвая, жизнь, какаято, такая, стрёмная, арт...  
8      1281551551706865665                                         [красивый]  
9      1257761690122358784                                      [цыган, хуле]  
11     1236273859671834624               [очень, красиво, чувственно, пишешь]  
...                    ...                                                ...  
13382  1284435123144994816                        [не, знаю, сказать, просто]  
13384  1249422155487629313         [ладно, всё, делаю, это, ваше, сраное, дз]  
13385  1237630704449736705  [66летняя, женщина, пострадала, пожаре, улице,...  
13387  1310349554911457286               [пора, спать, пиздец, словила, шизу]  
13390  1308341976455053312                                      [пиздануться]  

[5712 rows x 4 columns]

## Осуществите стемминг подготовленного набора данных и преобразуйте каждый твит в мешок слов.

In [129]:
from nltk.stem import SnowballStemmer

snowball = SnowballStemmer(language="russian")

def stemm(words):
    stemmed = []
    for word in words:
        stemmed.append(snowball.stem(word))
    return stemmed

df.loc[:, 'stemmed_text'] = df['clean_text'].apply(stemm)
df

C:\Users\an23m\AppData\Local\Temp\ipykernel_12896\4093544202.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'stemmed_text'] = df['clean_text'].apply(stemm)


text     label  \
1      велл они  всё равно что мусор так что ничего с...  negative   
2      "трезвая жизнь какая-то такая стрёмная"\r\n(с)...  negative   
8                       @BTS_twt ты такой красивый 😭😭😭🥺💓  positive   
9                          @Ladyzchensk Цыган , хуле ...  negative   
11     @okdaa @wifeyoonminn @Y_Yoon_ Но ты очень крас...  positive   
...                                                  ...       ...   
13382  @_sasukedaisuki_ я не знаю что сказать просто\...  positive   
13384                 ладно всё делаю это ваше сраное дз  negative   
13385  66-летняя женщина пострадала на пожаре на улиц...  negative   
13387                 все пора спать пиздец словила шизу  negative   
13390                         @AlyonaPikachu Пиздануться  negative   

                        id                                         clean_text  \
1      1252943181387350017               [велл, всё, равно, мусор, страшного]   
2      1323610669061677056  [трезвая, жизнь, какаято, такая, стрёмная, арт...   
8      1281551551706865665                                         [красивый]   
9      1257761690122358784                                      [цыган, хуле]   
11     1236273859671834624               [очень, красиво, чувственно, пишешь]   
...                    ...                                                ...   
13382  1284435123144994816                        [не, знаю, сказать, просто]   
13384  1249422155487629313         [ладно, всё, делаю, это, ваше, сраное, дз]   
13385  1237630704449736705  [66летняя, женщина, пострадала, пожаре, улице,...   
13387  1310349554911457286               [пора, спать, пиздец, словила, шизу]   
13390  1308341976455053312                                      [пиздануться]   

                                            stemmed_text  
1                       [велл, все, равн, мусор, страшн]  
2       [трезв, жизн, какаят, так, стремн, арт, azrtusa]  
8                                               [красив]  
9                                            [цыга, хул]  
11                       [очен, красив, чувствен, пишеш]  
...                                                  ...  
13382                            [не, зна, сказа, прост]  
13384               [ладн, все, дела, эт, ваш, сран, дз]  
13385  [66летн, женщин, пострада, пожар, улиц, коровн...  
13387                     [пор, спат, пиздец, слов, шиз]  
13390                                         [пизданут]  

[5712 rows x 5 columns]

In [130]:
from sklearn.model_selection import train_test_split

X = df['stemmed_text'].apply(lambda x: ' '.join(x)) # count_vectorizer получает на вход строку
y = df['label'].map({'negative': 0, 'positive': 1})

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 32, stratify=y)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

# Преобразуем текст в мешок слов
X_train_vectorized = vectorizer.fit_transform(X_train)

print(vectorizer.get_feature_names_out())

print(X_train_vectorized.toarray())
X_train_vectorized.toarray()[0].shape

['000' '0000' '026' ... 'マギ' '세븐틴' '에이티즈']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(8806,)

In [132]:
X_test_vectorized = vectorizer.transform(X_test)
print(X_test_vectorized.toarray())
X_test_vectorized.toarray()[0].shape

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(8806,)

## Составьте Count-матрицу и рассчитайте на ней tf-idf.

In [133]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_vectorized)
X_test_tfidf = tfidf_transformer.transform(X_test_vectorized)

X_train_tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## Обучите модели логистической регрессии и случайного леса на обучающей выборке, примените их к тестовым данным.

In [134]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, StratifiedKFold
import numpy as np

log_reg = LogisticRegression(max_iter=100)

param_grid = {'C': [0.01, 0.1, 0.5, 1, 5, 10, 20, 50, 100]}

stratified_kfold = StratifiedKFold(n_splits=5)
grid_search = GridSearchCV(log_reg, param_grid, cv=stratified_kfold, scoring='f1')

grid_search.fit(X_train_tfidf, y_train)

best_C = grid_search.best_params_['C']
grid_search

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [0.01, 0.1, 0.5, 1, 5, 10, 20, 50, 100]},
             scoring='f1')

In [135]:
log_reg = LogisticRegression(max_iter=100, C=best_C)
log_reg.fit(X_train_tfidf, y_train)
y_pred = log_reg.predict(X_test_tfidf)

In [136]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

ac = accuracy_score(y_pred, y_test)
pr = precision_score(y_pred, y_test)
rec = recall_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test)
print(f'Accuracy: {ac}, Precision: {pr}, Recall: {rec}, F1: {f1}')

Accuracy: 0.7821522309711286, Precision: 0.6666666666666666, Recall: 0.7853658536585366, F1: 0.7211646136618141


In [137]:
## train
y_pred_train = log_reg.predict(X_train_tfidf)
ac = accuracy_score(y_pred_train, y_train)
pr = precision_score(y_pred_train, y_train)
rec = recall_score(y_pred_train, y_train)
f1 = f1_score(y_pred_train, y_train)
print(f'Accuracy: {ac}, Precision: {pr}, Recall: {rec}, F1: {f1}')

Accuracy: 0.9905887502735828, Precision: 0.983946141895391, Recall: 0.9937238493723849, F1: 0.9888108248763986


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

rand_forest = RandomForestClassifier(random_state=10, class_weight="balanced")

# Параметры для случайного поиска
param_dist = {
    'n_estimators': randint(100, 500), # Количество деревьев
    'max_depth': randint(10, 30),  # Глубина деревьев
    'min_samples_split': randint(2, 10),
    'min_samples_leaf': randint(1, 5)
}

# Случайный поиск по гиперпараметрам
rand_search = RandomizedSearchCV(rand_forest, param_dist, n_iter=50, cv=5, scoring='f1', random_state=10)
rand_search.fit(X_train_tfidf, y_train)

# Лучшие параметры
best_params = rand_search.best_params_

Accuracy: 0.6999125109361329
Precision: 0.610062893081761
Recall: 0.8033126293995859
F1: 0.6934763181411975


In [153]:
best_params

{'max_depth': 22,
 'min_samples_leaf': 2,
 'min_samples_split': 9,
 'n_estimators': 413}

In [154]:
ran_forest = rand_forest.set_params(**best_params)
ran_forest.fit(X_train_tfidf, y_train)
y_pred = ran_forest.predict(X_test_tfidf)

In [155]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

ac = accuracy_score(y_pred, y_test)
pr = precision_score(y_pred, y_test)
rec = recall_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test)
print(f'Accuracy: {ac}, Precision: {pr}, Recall: {rec}, F1: {f1}')

Accuracy: 0.6999125109361329, Precision: 0.8033126293995859, Recall: 0.610062893081761, F1: 0.6934763181411975


In [156]:
y_pred_train = ran_forest.predict(X_train_tfidf)
ac = accuracy_score(y_pred_train, y_train)
pr = precision_score(y_pred_train, y_train)
rec = recall_score(y_pred_train, y_train)
f1 = f1_score(y_pred_train, y_train)
print(f'Accuracy: {ac}, Precision: {pr}, Recall: {rec}, F1: {f1}')

Accuracy: 0.7767564018384767, Precision: 0.8741584671154842, Recall: 0.6847870182555781, F1: 0.7679708826205641


## Найти наиболее важные признаки (слова)

In [159]:
feature_names = vectorizer.get_feature_names_out() 
feature_names

array(['000', '0000', '026', ..., 'マギ', '세븐틴', '에이티즈'], dtype=object)

In [160]:
top_10_indices_log_reg = np.argsort(np.abs(log_reg.coef_[0]))[-10:]

top_10_words_log_reg = [(feature_names[i], log_reg.coef_[0][i]) for i in top_10_indices_log_reg]

print("Топ-10 важных слов по модели логистической регрессии:")
for word, coef in top_10_words_log_reg:
    print(f"{word}: {coef}")

Топ-10 важных слов по модели логистической регрессии:
крут: 5.435455201152594
пиздец: -5.962244625176241
прекрасн: 6.108001544142436
классн: 6.347310251032447
красив: 6.4196354595306735
мил: 6.484369870487307
хорош: 6.548298940083877
любл: 6.676083559220755
нах: -6.748555650744753
блят: -7.372706883287876


In [161]:
top_10_indices_forest = np.argsort(ran_forest.feature_importances_)[-10:]

top_10_words_forest = [(feature_names[i], ran_forest.feature_importances_[i]) for i in top_10_indices_forest]

print("Топ-10 важных слов по модели случайного леса:")
for word, importance in top_10_words_forest:
    print(f"{word}: {importance}")

Топ-10 важных слов по модели случайного леса:
мил: 0.017590501358475
прекрасн: 0.018177660043656636
нет: 0.01842264814200677
нах: 0.020340362318909958
красив: 0.022814234876096132
пиздец: 0.03157118539001806
хорош: 0.036276414295270495
любл: 0.03808554223050778
блят: 0.03929123932217857
не: 0.05555062800357881


## Вместо стемминга осуществите лемматизацию и проделайте пункты 3-5 с учетом другого типа подготовки данных.

In [163]:
import spacy

rus_words = spacy.load("ru_core_news_sm")


def lemma(words):
    text = " ".join(words)
    doc = rus_words(text)
    lemmas = [token.lemma_ for token in doc]
    return lemmas

df.loc[:, 'lemmed_text'] = df['clean_text'].apply(lemma)
df

C:\Users\an23m\AppData\Local\Temp\ipykernel_12896\4238088617.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'lemmed_text'] = df['clean_text'].apply(lemma)


text     label  \
1      велл они  всё равно что мусор так что ничего с...  negative   
2      "трезвая жизнь какая-то такая стрёмная"\r\n(с)...  negative   
8                       @BTS_twt ты такой красивый 😭😭😭🥺💓  positive   
9                          @Ladyzchensk Цыган , хуле ...  negative   
11     @okdaa @wifeyoonminn @Y_Yoon_ Но ты очень крас...  positive   
...                                                  ...       ...   
13382  @_sasukedaisuki_ я не знаю что сказать просто\...  positive   
13384                 ладно всё делаю это ваше сраное дз  negative   
13385  66-летняя женщина пострадала на пожаре на улиц...  negative   
13387                 все пора спать пиздец словила шизу  negative   
13390                         @AlyonaPikachu Пиздануться  negative   

                        id                                         clean_text  \
1      1252943181387350017               [велл, всё, равно, мусор, страшного]   
2      1323610669061677056  [трезвая, жизнь, какаято, такая, стрёмная, арт...   
8      1281551551706865665                                         [красивый]   
9      1257761690122358784                                      [цыган, хуле]   
11     1236273859671834624               [очень, красиво, чувственно, пишешь]   
...                    ...                                                ...   
13382  1284435123144994816                        [не, знаю, сказать, просто]   
13384  1249422155487629313         [ладно, всё, делаю, это, ваше, сраное, дз]   
13385  1237630704449736705  [66летняя, женщина, пострадала, пожаре, улице,...   
13387  1310349554911457286               [пора, спать, пиздец, словила, шизу]   
13390  1308341976455053312                                      [пиздануться]   

                                            stemmed_text  \
1                       [велл, все, равн, мусор, страшн]   
2       [трезв, жизн, какаят, так, стремн, арт, azrtusa]   
8                                               [красив]   
9                                            [цыга, хул]   
11                       [очен, красив, чувствен, пишеш]   
...                                                  ...   
13382                            [не, зна, сказа, прост]   
13384               [ладн, все, дела, эт, ваш, сран, дз]   
13385  [66летн, женщин, пострада, пожар, улиц, коровн...   
13387                     [пор, спат, пиздец, слов, шиз]   
13390                                         [пизданут]   

                                             lemmed_text  
1                   [велл, всё, равный, мусор, страшный]  
2      [трезвый, жизнь, какаято, такой, стрёмный, арт...  
8                                             [красивый]  
9                                          [цыган, хуле]  
11                  [очень, красиво, чувственно, писать]  
...                                                  ...  
13382                       [не, знать, сказать, просто]  
13384         [ладно, всё, делать, это, ваш, сраное, дз]  
13385  [66летняя, женщина, пострадать, пожар, улица, ...  
13387               [пора, спать, пиздец, словила, шизу]  
13390                                      [пиздануться]  

[5712 rows x 6 columns]

In [164]:
from sklearn.model_selection import train_test_split

X = df['lemmed_text'].apply(lambda x: ' '.join(x)) # count_vectorizer получает на вход строку
y = df['label'].map({'negative': 0, 'positive': 1})

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 32, stratify=y)

In [165]:
vectorizer = CountVectorizer()

# Преобразуем текст в мешок слов
X_train_vectorized = vectorizer.fit_transform(X_train)

print(vectorizer.get_feature_names_out())

print(X_train_vectorized.toarray())
X_train_vectorized.toarray()[0].shape

['000' '0000' '026' ... 'マギ' '세븐틴' '에이티즈']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(9836,)

In [166]:
X_test_vectorized = vectorizer.transform(X_test)
print(X_test_vectorized.toarray())
X_test_vectorized.toarray()[0].shape

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(9836,)

In [167]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_vectorized)
X_test_tfidf = tfidf_transformer.transform(X_test_vectorized)

X_train_tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [172]:
log_reg = LogisticRegression(max_iter=100)

param_grid = {'C': [0.01, 0.1, 0.5, 1, 5, 10, 20, 30, 50, 100]}

stratified_kfold = StratifiedKFold(n_splits=5)
grid_search = GridSearchCV(log_reg, param_grid, cv=stratified_kfold, scoring='f1')

grid_search.fit(X_train_tfidf, y_train)

best_C = grid_search.best_params_['C']
grid_search

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [0.01, 0.1, 0.5, 1, 5, 10, 20, 30, 50, 100]},
             scoring='f1')

In [169]:
log_reg = LogisticRegression(max_iter=100, C=best_C)
log_reg.fit(X_train_tfidf, y_train)
y_pred = log_reg.predict(X_test_tfidf)

In [170]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

ac = accuracy_score(y_pred, y_test)
pr = precision_score(y_pred, y_test)
rec = recall_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test)
print(f'Accuracy: {ac}, Precision: {pr}, Recall: {rec}, F1: {f1}')

Accuracy: 0.7637795275590551, Precision: 0.6459627329192547, Recall: 0.7591240875912408, F1: 0.697986577181208


In [171]:
## train
y_pred_train = log_reg.predict(X_train_tfidf)
ac = accuracy_score(y_pred_train, y_train)
pr = precision_score(y_pred_train, y_train)
rec = recall_score(y_pred_train, y_train)
f1 = f1_score(y_pred_train, y_train)
print(f'Accuracy: {ac}, Precision: {pr}, Recall: {rec}, F1: {f1}')

Accuracy: 0.9960604070912672, Precision: 0.9943034697048162, Recall: 0.9963674104826155, F1: 0.995334370139969


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

rand_forest = RandomForestClassifier(random_state=10, class_weight="balanced")

# Параметры для случайного поиска
param_dist = {
    'n_estimators': randint(100, 500), # Количество деревьев
    'max_depth': randint(10, 30),  # Глубина деревьев
    'min_samples_split': randint(2, 10),
    'min_samples_leaf': randint(1, 5)
}

# Случайный поиск по гиперпараметрам
rand_search = RandomizedSearchCV(rand_forest, param_dist, n_iter=30, cv=5, scoring='f1', random_state=10)
rand_search.fit(X_train_tfidf, y_train)

# Лучшие параметры
best_params = rand_search.best_params_

In [ ]:
best_params

{'max_depth': 22,
 'min_samples_leaf': 2,
 'min_samples_split': 9,
 'n_estimators': 413}

In [ ]:
ran_forest = rand_forest.set_params(**best_params)
ran_forest.fit(X_train_tfidf, y_train)
y_pred = ran_forest.predict(X_test_tfidf)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

ac = accuracy_score(y_pred, y_test)
pr = precision_score(y_pred, y_test)
rec = recall_score(y_pred, y_test)
f1 = f1_score(y_pred, y_test)
print(f'Accuracy: {ac}, Precision: {pr}, Recall: {rec}, F1: {f1}')

Accuracy: 0.6999125109361329, Precision: 0.8033126293995859, Recall: 0.610062893081761, F1: 0.6934763181411975


In [ ]:
y_pred_train = ran_forest.predict(X_train_tfidf)
ac = accuracy_score(y_pred_train, y_train)
pr = precision_score(y_pred_train, y_train)
rec = recall_score(y_pred_train, y_train)
f1 = f1_score(y_pred_train, y_train)
print(f'Accuracy: {ac}, Precision: {pr}, Recall: {rec}, F1: {f1}')

Accuracy: 0.7767564018384767, Precision: 0.8741584671154842, Recall: 0.6847870182555781, F1: 0.7679708826205641


## Сравните результаты по качеству и по наиболее важным признакам (словам) между 2 обученными вариантами.